SET DEFINE OFF;
DELETE FROM TAPPLSCR WHERE CODAPP='HRMS89U0';
DELETE FROM TAPPLSCR WHERE CODAPP='HRMS89U1';
DELETE FROM TAPPLSCR WHERE CODAPP='HRMS89U2';
INSERT INTO TAPPLSCR VALUES ('HRMS89U0',10,NULL,'Date Approve From','วันที่อนุมัติตั้งแต่','Date Approve From','Date Approve From','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U0',20,NULL,'To Date','ถึงวันที่','To Date','To Date','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U0',30,NULL,'Approve Status','สถานะการอนุมัติ','Approve Status','Approve Status','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U0',40,NULL,'Employee ID','รหัสพนักงาน','Employee ID','Employee ID','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U1',10,NULL,'Employee ID','รหัสพนักงาน','Employee ID','Employee ID','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U1',20,NULL,'Approve Status','สถานะการอนุมัติ','Approve Status','Approve Status','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U1',30,NULL,'Date Approve From','วันที่อนุมัติตั้งแต่','Date Approve From','Date Approve From','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U1',40,NULL,'To Date','ถึงวันที่','To Date','To Date','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U1',50,NULL,'Image','รูป','Image','Image','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U1',60,NULL,'Employee Name','ชื่อ - นามสกุล','Employee Name','Employee Name','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U1',70,NULL,'Req. Date','วันที่ขอ','Req. Date','Req. Date','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U1',80,NULL,'No.','ลำดับคำร้อง','No.','No.','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U1',90,NULL,'Department','หน่วยงาน','Department','Department','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U1',100,NULL,'Position','ตำแหน่ง','Position','Position','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U1',110,NULL,'Request rate','อัตราที่ขอ','Request rate','Request rate','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U1',120,NULL,'Approval by','ขออนุมัติโดย','Approval by','Approval by','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U1',130,NULL,'Status','สถานะ','Status','Status','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U1',140,NULL,'Approved By','ผู้อนุมัติ','Approved By','Approved By','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U1',150,NULL,'Appr.Date','วันที่อนุมัติ','Appr.Date','Appr.Date','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U1',160,NULL,'Remark','หมายเหตุการอนุมัติ','Remark','Remark','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U1',170,NULL,'Next Approve','ผู้อนุมัติลำดับถัดไป','Next Approve','Next Approve','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U1',180,NULL,'Applicant code','รหัสผู้รับสมัคร','Applicant code','Applicant code','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U1',190,NULL,'Date of application','วันที่เปิดรับสมัคร','Date of application','Date of application','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U1',200,NULL,'Application deadline','วันที่ปิดรับสมัคร','Application deadline','Application deadline','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U1',210,NULL,'Approval Details','รายละเอียดการอนุมัติ','Approval Details','Approval Details','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U1',220,NULL,'Approval order','ลำดับที่อนุมัติ','Approval order','Approval order','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U1',230,NULL,'Approved by','อนุมัติโดย','Approved by','Approved by','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U1',240,NULL,'Status','สถานะปัจจุบัน','Status','Status','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U1',250,NULL,'Remark','หมายเหตุ','Remark','Remark','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U1',260,NULL,'Approval date','วันที่ขออนุมัติ','Approval date','Approval date','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U1',270,NULL,'For Department','สำหรับหน่วยงาน','For Department','For Department','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U2',10,NULL,'Approved By','ผู้อนุมัติ','Approved By','Approved By','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U2',20,NULL,'Req. Date','วันที่ขอ','Req. Date','Req. Date','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U2',30,NULL,'Department','สำหรับหน่วยงาน','Department','Department','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U2',40,NULL,'Position','ตำแหน่ง','Position','Position','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U2',50,NULL,'Request No.','เลขที่ใบขออนุมัติ','Request No.','Request No.','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U2',60,NULL,'Approval details','รายละเอียดการขออนุมัติ','Approval details','Approval details','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U2',70,NULL,'Job Description','ลักษณะงาน','Job Description','Job Description','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U2',80,NULL,'Employment Type','ประเภทการจ้างงาน','Employment Type','Employment Type','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U2',90,NULL,'Branch required','สาขาที่ต้องการ','Branch required','Branch required','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U2',100,NULL,'Salary','เงินเดือนที่จัดจ้าง','Salary','Salary','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U2',110,NULL,'Request from','ขอจาก','Request from','Request from','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U2',120,NULL,'Amount Requested','จำนวนคนที่ขอ','Amount Requested','Amount Requested','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U2',130,NULL,'Require Date','วันที่ต้องการ','Require Date','Require Date','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U2',140,NULL,'Received Date','วันที่รับ','Received Date','Received Date','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U2',150,NULL,'Application deadline','วันที่ปิดรับสมัคร','Application deadline','Application deadline','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U2',160,NULL,'Over Due (Day)','Over Due (วัน)','Over Due (Day)','Over Due (Day)','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U2',170,NULL,'Reason of request','สาเหตุการขอ','Reason of request','Reason of request','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U2',180,NULL,'Instead of employee code','แทนรหัสพนักงาน','Instead of employee code','Instead of employee code','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U2',190,NULL,'Qualifications','คุณสมบัติที่ต้องการ','Qualifications','Qualifications','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U2',200,NULL,'Job description','ตามลักษณะงาน','Job description','Job description','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U2',210,NULL,'Detail','รายละเอียด','Detail','Detail','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U2',220,NULL,'Newly set up','กำหนดขึ้นใหม่','Newly set up','Newly set up','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U2',230,NULL,'Condition','เงื่อนไข','Condition','Condition','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U2',240,NULL,'Remark','หมายเหตุ','Remark','Remark','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U2',250,NULL,'baht','บาท','baht','baht','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U2',260,NULL,'Yes','Yes','Yes','Yes','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U2',270,NULL,'No','No','No','No','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U2',280,NULL,'File Job Description','ไฟล์ Job Description','File Job Description','File Job Description','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRMS89U2',290,NULL,'File Organization Chart','ไฟล์ Organization Chart','File Organization Chart','File Organization Chart','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
commit;
