SET DEFINE OFF;
DELETE FROM TAPPLSCR WHERE CODAPP='HRRC11E0';
DELETE FROM TAPPLSCR WHERE CODAPP='HRRC11E1';
DELETE FROM TAPPLSCR WHERE CODAPP='HRRC11E2';
DELETE FROM TAPPLSCR WHERE CODAPP='HRRC11E3';
DELETE FROM TAPPLSCR WHERE CODAPP='HRRC11E4';
DELETE FROM TAPPLSCR WHERE CODAPP='HRRC11E5';
DELETE FROM TAPPLSCR WHERE CODAPP='HRRC11E6';
INSERT INTO TAPPLSCR VALUES ('HRRC11E0',10,NULL,'Department code','รหัสหน่วยงาน','Department code','Department code','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E0',20,NULL,'Date open for request','วันที่เปิดขอ','Date open for request','Date open for request','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E0',30,NULL,'To date','ถึงวันที่','To date','To date','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E0',40,NULL,'Applicant code','รหัสผู้รับสมัคร','Applicant code','Applicant code','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E0',50,NULL,'Request status','สถานะใบคำขอ','Request status','Request status','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E1',10,NULL,'Department code','รหัสหน่วยงาน','Department code','Department code','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E1',20,NULL,'Date open for request','วันที่เปิดขอ','Date open for request','Date open for request','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E1',30,NULL,'To date','ถึงวันที่','To date','To date','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E1',40,NULL,'Applicant code','รหัสผู้รับสมัคร','Applicant code','Applicant code','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E1',50,NULL,'Request status','สถานะใบคำขอ','Request status','Request status','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E1',60,NULL,'Department name','ชื่อหน่วยงาน','Department name','Department name','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E1',70,NULL,'Approval number','เลขที่ใบขออนุมัติ','Approval number','Approval number','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E1',80,NULL,'Department','หน่วยงาน','Department','Department','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E1',90,NULL,'Applicant name','ชื่อผู้รับสมัคร','Applicant name','Applicant name','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E1',100,NULL,'Detail information','รายละเอียดข้อมูล','Detail information','Detail information','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E2',10,NULL,'Approval number','เลขที่ใบขออนุมัติ','Approval number','Approval number','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E2',20,NULL,'Copy Comes from the application number','Copy มาจากเลขที่ใบคำขอ','Copy Comes from the application number','Copy Comes from the application number','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E2',30,NULL,'Detail 1','รายละเอียด 1','Detail 1','Detail 1','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E2',40,NULL,'Department requested','หน่วยงานที่ขอ','Department requested','Department requested','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E2',50,NULL,'Authorization Code','รหัสผู้ขออนุมัติ','Authorization Code','Authorization Code','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E2',60,NULL,'Date requested','วันที่ขอ','Date requested','Date requested','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E2',70,NULL,'Approved by','อนุมัติโดย','Approved by','Approved by','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E2',80,NULL,'Date Approve','วันที่อนุมัติ','Date Approve','Date Approve','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E2',90,NULL,'Applicant code','รหัสผู้รับสมัคร','Applicant code','Applicant code','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E2',100,NULL,'Applicant code for interview','รหัสผู้ขออนุมัติคัดเลือกเพื่อเรียกสัมภาษณ์','Applicant code for interview','Applicant code for interview','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E2',110,NULL,'Applicant Code for Adoption','รหัสผู้ขออนุมัติคัดเลือกเพื่อการรับเข้าทำงาน','Applicant Code for Adoption','Applicant Code for Adoption','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E2',120,NULL,'Remark','หมายเหตุ','Remark','Remark','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E2',130,NULL,'Latest request status','สถานะใบคำขอล่าสุด','Latest request status','Latest request status','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E2',140,NULL,'Last action date','วันที่ดำเนินการล่าสุด','Last action date','Last action date','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E2',150,NULL,'Jobs Descrption','Jobs Descrption','Jobs Descrption','Jobs Descrption','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E2',160,NULL,'Organizatiion Chart','Organizatiion Chart','Organizatiion Chart','Organizatiion Chart','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E3',10,NULL,'Detail 2','รายละเอียด 2','Detail 2','Detail 2','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E3',20,NULL,'Requested position','ตำแหน่งที่ขอ','Requested position','Requested position','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E3',30,NULL,'job description','ลักษณะงาน','job description','job description','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E3',40,NULL,'Employment type','ประเภทการจ้างงาน','Employment type','Employment type','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E3',50,NULL,'Branch required','สาขาที่ต้องการ','Branch required','Branch required','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E3',60,NULL,'Salary','เงินเดือนที่จัดจ้าง','Salary','Salary','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E3',70,NULL,'Baht','บาท','Baht','Baht','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E3',80,NULL,'Request from','ขอจาก','Request from','Request from','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E3',90,NULL,'Job Posting List','รายการ Job Posting','Job Posting List','Job Posting List','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E3',100,NULL,'Date Post','วันที่ Post','Date Post','Date Post','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E3',110,NULL,'Date of application','วันที่เปิดรับสมัคร','Date of application','Date of application','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E3',120,NULL,'Qualifications','คุณสมบัติที่ต้องการ','Qualifications','Qualifications','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E3',130,NULL,'According to work characteristics','ตามลักษณะงาน','According to work characteristics','According to work characteristics','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E3',140,NULL,'Job Specification','Job Specification','Job Specification','Job Specification','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E3',150,NULL,'Desired date','วันที่ต้องการ','Desired date','Desired date','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E3',160,NULL,'Opening date','วันที่เปิดรับ','Opening date','Opening date','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E3',170,NULL,'Over Due (Day)','Over Due (วัน)','Over Due (Day)','Over Due (Day)','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E3',180,NULL,'Request reason','สาเหตุการขอ','Request reason','Request reason','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E3',190,NULL,'Instead of employee code','แทนรหัสพนักงาน','Instead of employee code','Instead of employee code','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E3',200,NULL,'source','แหล่งข่าว','source','source','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E3',210,NULL,'Newly set up','กำหนดขึ้นใหม่','Newly set up','Newly set up','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E3',220,NULL,'Number of people requesting','จำนวนคนที่ขอ','Number of people requesting','Number of people requesting','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E3',230,NULL,'Number of applicants','จำนวนผู้สมัคร','Number of applicants','Number of applicants','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E3',240,NULL,'allocate','จัดสรร','allocate','allocate','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E3',250,NULL,'balance','คงเหลือ','balance','balance','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E3',260,NULL,'person','คน','person','person','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E3',270,NULL,'Application closing date','วันที่ปิดรับสมัคร','Application closing date','Application closing date','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E3',280,NULL,'Benefits received','สวัสดิการที่ได้รับ','Benefits received','Benefits received','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E4',10,NULL,'Number of applicants','จำนวนผู้สมัคร','Number of applicants','Number of applicants','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E4',20,NULL,'Total number of applicants','จำนวนผู้สมัครทั้งหมด','Total number of applicants','Total number of applicants','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E4',30,NULL,'Status','สถานะ','Status','Status','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E4',40,NULL,'number of people','จำนวนคน','number of people','number of people','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E4',50,NULL,'Date Update Last','วันที่ Update ล่าสุด','Date Update Last','Date Update Last','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E4',60,NULL,'person','คน','person','person','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E5',10,NULL,'Candidate list','รายชื่อผู้สมัคร','Candidate list','Candidate list','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E5',20,NULL,'Total number of applicants','จำนวนผู้สมัครทั้งหมด','Total number of applicants','Total number of applicants','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E5',30,NULL,'Application number','เลขที่ใบสมัคร','Application number','Application number','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E5',40,NULL,'Emp. code','รหัสพนักงาน','Emp. code','Emp. code','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E5',50,NULL,'Name','ชื่อผู้สมัคร','Name','Name','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E5',60,NULL,'Status','สถานะ','Status','Status','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E5',70,NULL,'Date Update Last','วันที่ Update ล่าสุด','Date Update Last','Date Update Last','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E5',80,NULL,'person','คน','person','person','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E5',90,NULL,'Position','ตำแหน่ง','Position','Position','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E5',100,NULL,'Number of people','จำนวนคน','Number of people','Number of people','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E6',10,NULL,'List of selected candidates','รายชื่อผู้สมัครที่ได้รับเลือก','List of selected candidates','List of selected candidates','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E6',20,NULL,'Request number','เลขที่ใบขอ','Request number','Request number','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E6',30,NULL,'Position','ตำแหน่ง','Position','Position','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E6',40,NULL,'Applicant code','รหัสผู้รับสมัคร','Applicant code','Applicant code','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E6',50,NULL,'Applicant name','ชื่อผู้รับสมัคร','Applicant name','Applicant name','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E6',60,NULL,'Amount requested','จำนวนที่ขอ','Amount requested','Amount requested','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E6',70,NULL,'Numseq','ลำดับที่','Numseq','Numseq','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E6',80,NULL,'Application number','เลขที่ใบสมัคร','Application number','Application number','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E6',90,NULL,'Name','ชื่อ - นามสกุล','Name','Name','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E6',100,NULL,'Salary','เงินเดือนที่จ้าง','Salary','Salary','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC11E6',110,NULL,'Start date','วันที่เริ่มงาน','Start date','Start date','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
commit;
