SET DEFINE OFF;
DELETE FROM TAPPLSCR WHERE CODAPP='HRRC14X0';
DELETE FROM TAPPLSCR WHERE CODAPP='HRRC14X1';
INSERT INTO TAPPLSCR VALUES ('HRRC14X0',10,NULL,'Company Request','หน่วยงานที่ขอ','Company Request','Company Request','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC14X0',20,NULL,'Date Requested','วันที่ขอ','Date Requested','Date Requested','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC14X0',30,NULL,'Up to date','ถึงวันที่','Up to date','Up to date','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC14X0',40,NULL,'Application code','รหัสผู้รับสมัคร','Application code','Application code','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC14X0',50,NULL,'Application status','สถานะใบขออนุมัติ','Application status','Application status','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC14X1',10,NULL,'Code Applicant','รหัสผู้รับสมัคร','Code Applicant','Code Applicant','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC14X1',20,NULL,'Company Request','ชื่อหน่วยงานที่ขอ','Company Request','Company Request','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC14X1',30,NULL,'Date Requested','วันที่ขอ','Date Requested','Date Requested','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC14X1',40,NULL,'To date','ถึงวันที่','To date','To date','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC14X1',50,NULL,'Status','สถานะใบขออนุมัติ','Status','Status','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC14X1',60,NULL,'Request No.','เลขที่ใบขอ','Request No.','Request No.','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC14X1',70,NULL,'Applicant Name','ชื่อผู้รับสมัคร','Applicant Name','Applicant Name','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC14X1',80,NULL,'Position','ตำแหน่ง','Position','Position','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC14X1',90,NULL,'Desired date','วันที่ต้องการ','Desired date','Desired date','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC14X1',100,NULL,'Desired Requested','อัตราที่ขอ','Desired Requested','Desired Requested','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC14X1',110,NULL,'Amount Requested','จำนวนที่จัดสรร','Amount Requested','Amount Requested','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC14X1',120,NULL,'Informed Source','แหล่งข่าว','Informed Source','Informed Source','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC14X1',130,NULL,'Date Post','วันที่ Post','Date Post','Date Post','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRC14X1',140,NULL,'Date Expire','วันที่ Expire','Date Expire','Date Expire','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
commit;
