SET DEFINE OFF;
DELETE FROM TAPPLSCR WHERE CODAPP='HRES88E0';
DELETE FROM TAPPLSCR WHERE CODAPP='HRES88E1';
DELETE FROM TAPPLSCR WHERE CODAPP='HRES88E2';
INSERT INTO TAPPLSCR VALUES ('HRES88E0',10,NULL,'Request Date From','วันที่ขอตั้งแต่','Request Date From','Request Date From','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRES88E0',20,NULL,'To','ถึง','To','To','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRES88E1',10,NULL,'Request Date From','วันที่ขอตั้งแต่','Request Date From','Request Date From','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRES88E1',20,NULL,'To','ถึง','To','To','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRES88E1',30,NULL,'Employee ID.','รหัสพนักงาน','Employee ID.','Employee ID.','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRES88E1',40,NULL,'Request date','วันที่ขอ','Request date','Request date','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRES88E1',50,NULL,'No.','ลำดับที่','No.','No.','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRES88E1',60,NULL,'Department','หน่วยงาน','Department','Department','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRES88E1',70,NULL,'Position','ตำแหน่ง','Position','Position','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRES88E1',80,NULL,'Requested amount','จำนวนที่ขอ','Requested amount','Requested amount','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRES88E1',90,NULL,'Status','สถานะ','Status','Status','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRES88E1',100,NULL,'Remark','หมายเหตุ','Remark','Remark','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRES88E1',110,NULL,'Last Approver','ผู้อนุมัติล่าสุด','Last Approver','Last Approver','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRES88E1',120,NULL,'Next Step Approval','ผู้อนุมัติลำดับถัดไป','Next Step Approval','Next Step Approval','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRES88E2',10,NULL,'Requesting agency','หน่วยงานที่ขอ','Requesting agency','Requesting agency','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRES88E2',20,NULL,'Requested position','ตำแหน่งที่ขอ','Requested position','Requested position','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRES88E2',30,NULL,'job description','ลักษณะงาน','job description','job description','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRES88E2',40,NULL,'Employment type','ประเภทการจ้างงาน','Employment type','Employment type','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRES88E2',50,NULL,'Branch required','สาขาที่ต้องการ','Branch required','Branch required','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRES88E2',60,NULL,'Salary','เงินเดือนที่จัดจ้าง','Salary','Salary','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRES88E2',70,NULL,'Baht','บาท','Baht','Baht','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRES88E2',80,NULL,'Request from','ขอจาก','Request from','Request from','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRES88E2',90,NULL,'Request reason','สาเหตุการขอ','Request reason','Request reason','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRES88E2',100,NULL,'Instead of employee code','แทนรหัสพนักงาน','Instead of employee code','Instead of employee code','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRES88E2',110,NULL,'Qualifications','คุณสมบัติที่ต้องการ','Qualifications','Qualifications','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRES88E2',120,NULL,'According to work characteristics','ตามลักษณะงาน','According to work characteristics','According to work characteristics','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRES88E2',130,NULL,'Newly set up','กำหนดขึ้นใหม่','Newly set up','Newly set up','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRES88E2',140,NULL,'Remark','หมายเหตุ','Remark','Remark','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRES88E2',150,NULL,'Number of people requesting','จำนวนคนที่ขอ','Number of people requesting','Number of people requesting','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRES88E2',160,NULL,'people','คน','people','people','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRES88E2',170,NULL,'Jobs Descrption','Jobs Descrption','Jobs Descrption','Jobs Descrption','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRES88E2',180,NULL,'Organizatiion Chart','Organizatiion Chart','Organizatiion Chart','Organizatiion Chart','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
commit;
