SET DEFINE OFF;
DELETE FROM TAPPLSCR WHERE CODAPP='STD_TREQESTP1';
DELETE FROM TAPPLSCR WHERE CODAPP='STD_TREQESTP2';
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP1',10,NULL,'Approval request details','รายละเอียดใบขออนุมัติ','Approval request details','Approval request details','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP1',20,NULL,'Application form number','เลขที่ใบขออนุมัติ','Application form number','Application form number','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP1',30,NULL,'Copy From the application number','Copy มาจากเลขที่ใบคำขอ','Copy From the application number','Copy From the application number','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP1',40,NULL,'Details 1','รายละเอียด 1','Details 1','Details 1','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP1',50,NULL,'Department Req.','หน่วยงานที่ขอ','Department Req.','Department Req.','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP1',60,NULL,'Requester Code','รหัสผู้ขออนุมัติ','Requester Code','Requester Code','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP1',70,NULL,'Date requested','วันที่ขอ','Date requested','Date requested','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP1',80,NULL,'Approved by','อนุมัติโดย','Approved by','Approved by','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP1',90,NULL,'Approval date','วันที่อนุมัติ','Approval date','Approval date','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP1',100,NULL,'Applicant code','รหัสผู้รับสมัคร','Applicant code','Applicant code','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP1',110,NULL,'Approval code for interview','รหัสผู้อนุมัติคัดเลือกเพื่อเรียกสัมภาษณ์','Approval code for interview','Approval code for interview','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP1',120,NULL,'Approval code of recruiter for employment','รหัสผู้อนุมัติคัดเลือกเพื่อการรับเข้าทำงาน','Approval code of recruiter for employment','Approval code of recruiter for employment','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP1',130,NULL,'Latest request status','สถานะใบคำขอล่าสุด','Latest request status','Latest request status','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP1',140,NULL,'Last action date','วันที่ดำเนินการล่าสุด','Last action date','Last action date','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP1',150,NULL,'Attached file','ไฟล์แนบ','Attached file','Attached file','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP1',160,NULL,'Remarks','หมายเหตุ','Remarks','Remarks','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP1',170,NULL,'New','ใหม่','New','New','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP1',180,NULL,'In progress','อยู่ระหว่างดำเนินการ','In progress','In progress','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP1',190,NULL,'Partially allocated','จัดสรรบางส่วน','Partially allocated','Partially allocated','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP1',200,NULL,'Allocated','จัดสรรครบ','Allocated','Allocated','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP1',210,NULL,'Cancel','ยกเลิก','Cancel','Cancel','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP1',220,NULL,'File Job Description','ไฟล์ Job Description','File Job Description','File Job Description','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP1',230,NULL,'File Organization Chart','ไฟล์ Organization Chart','File Organization Chart','File Organization Chart','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP2',10,NULL,'Details 2','รายละเอียด 2','Details 2','Details 2','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP2',20,NULL,'Position Req.','ตำแหน่งที่ขอ','Position Req.','Position Req.','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP2',30,NULL,'Job description','ลักษณะงาน','Job description','Job description','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP2',40,NULL,'Employment Type','ประเภทการจ้างงาน','Employment Type','Employment Type','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP2',50,NULL,'Branch Request','สาขาที่ต้องการ','Branch Request','Branch Request','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP2',60,NULL,'Salary','เงินเดือนที่จัดจ้าง','Salary','Salary','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP2',70,NULL,'Request from','ขอจาก','Request from','Request from','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP2',80,NULL,'Require Date','วันที่ต้องการ','Require Date','Require Date','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP2',90,NULL,'Received Date','วันที่รับ','Received Date','Received Date','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP2',100,NULL,'Application deadline','วันที่ปิดรับสมัคร','Application deadline','Application deadline','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP2',110,NULL,'Over Due (day)','Over Due (วัน)','Over Due (day)','Over Due (day)','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP2',120,NULL,'Reason of request','สาเหตุการขอ','Reason of request','Reason of request','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP2',130,NULL,'Instead of employee code','แทนรหัสพนักงาน','Instead of employee code','Instead of employee code','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP2',140,NULL,'Qualifications','คุณสมบัติที่ต้องการ','Qualifications','Qualifications','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP2',150,NULL,'Job description','ตามลักษณะงาน','Job description','Job description','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP2',160,NULL,'Details','รายละเอียด','Details','Details','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP2',170,NULL,'Remarks','หมายเหตุ','Remarks','Remarks','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP2',180,NULL,'Newly scheduled','กำหนดขึ้นใหม่','Newly scheduled','Newly scheduled','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP2',190,NULL,'Conditions ','เงื่อนไข','Conditions ','Conditions ','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP2',200,NULL,'Number of people requesting','จำนวนคนที่ขอ','Number of people requesting','Number of people requesting','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP2',210,NULL,'Allocate','จัดสรร','Allocate','Allocate','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP2',220,NULL,'Remain','คงเหลือ','Remain','Remain','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP2',230,NULL,'people','คน','people','people','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP2',240,NULL,'List Job Posting','รายการ Job Posting','List Job Posting','List Job Posting','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP2',250,NULL,'Date Post','วันที่ Post','Date Post','Date Post','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP2',260,NULL,'News source','แหล่งข่าว','News source','News source','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP2',270,NULL,'baht','บาท','baht','baht','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP2',300,NULL,'Not specified','ไม่ระบุ','Not specified','Not specified','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP2',310,NULL,'New position','ตำแหน่งใหม่','New position','New position','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP2',320,NULL,'Increase the rate','เพิ่มอัตรา','Increase the rate','Increase the rate','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP2',330,NULL,'Compensate','ทดแทน','Compensate','Compensate','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP2',340,NULL,'Other','อื่นๆ','Other','Other','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP2',380,NULL,'Internal','ภายใน','Internal','Internal','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('STD_TREQESTP2',390,NULL,'External','ภายนอก','External','External','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
commit;
