SET DEFINE OFF;
DELETE FROM TAPPLSCR WHERE CODAPP='HRRCZ1X1';
DELETE FROM TAPPLSCR WHERE CODAPP='HRRCZ1X_REPORT';
INSERT INTO TAPPLSCR VALUES ('HRRCZ1X1',10,NULL,'For Department Code','รหัสหน่วยงาน','For Department Code','For Department Code','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRCZ1X1',20,NULL,'Position requested','ตำแหน่งที่ขอ','Position requested','Position requested','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRCZ1X1',30,NULL,'Request Date','วันที่ขอ','Request Date','Request Date','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRRCZ1X1',40,NULL,'To Date','ถึงวันที่','To Date','To Date','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',101,NULL,'manpower Request Form','manpower Request Form','manpower Request Form','manpower Request Form','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',102,NULL,'Date of request','Date of request','Date of request','Date of request','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',103,NULL,'Requestor','Requestor','Requestor','Requestor','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',104,NULL,'Position request details','Position request details','Position request details','Position request details','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',105,NULL,'Position title (Eng)','Position title (Eng)','Position title (Eng)','Position title (Eng)','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',106,NULL,'Report to','Report to','Report to','Report to','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',107,NULL,'Division','Division','Division','Division','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',108,NULL,'Section','Section','Section','Section','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',109,NULL,'Working Time','Working Time','Working Time','Working Time','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',110,NULL,'5 Days','5 Days','5 Days','5 Days','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',111,NULL,'5.5 Days','5.5 Days','5.5 Days','5.5 Days','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',112,NULL,'6 Days','6 Days','6 Days','6 Days','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',113,NULL,'Job code','Job code','Job code','Job code','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',114,NULL,'Department','Department','Department','Department','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',115,NULL,'Work Location','Work Location','Work Location','Work Location','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',116,NULL,'Shift (from-to)','Shift (from-to)','Shift (from-to)','Shift (from-to)','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',201,NULL,'Reason for Manpower request','Reason for Manpower request','Reason for Manpower request','Reason for Manpower request','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',202,NULL,'1.1 Replacement of','1.1 Replacement of','1.1 Replacement of','1.1 Replacement of','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',203,NULL,'1.2 Replacement and change position from','1.2 Replacement and change position from','1.2 Replacement and change position from','1.2 Replacement and change position from','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',204,NULL,'1.3 Additional headcount with budget','1.3 Additional headcount with budget','1.3 Additional headcount with budget','1.3 Additional headcount with budget','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',205,NULL,'1.4 Additional headcount without a budget','1.4 Additional headcount without a budget','1.4 Additional headcount without a budget','1.4 Additional headcount without a budget','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',206,NULL,'Job Code','Job Code','Job Code','Job Code','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',207,NULL,'to','to','to','to','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',208,NULL,'Expected start work date','Expected start work date','Expected start work date','Expected start work date','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',209,NULL,'Please, Specify or attach support documents as below:','Please, Specify or attach support documents as below:','Please, Specify or attach support documents as below:','Please, Specify or attach support documents as below:','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',210,NULL,'1.Job description 2. Organization chart (if the reason for item 1.201.4 use new organization chart: draft version)','1.Job description 2. Organization chart (if the reason for item 1.201.4 use new organization chart: draft version)','1.Job description 2. Organization chart (if the reason for item 1.201.4 use new organization chart: draft version)','1.Job description 2. Organization chart (if the reason for item 1.201.4 use new organization chart: draft version)','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',211,NULL,'Employment type','Employment type','Employment type','Employment type','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',212,NULL,'Permanent','Permanent','Permanent','Permanent','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',213,NULL,'Temporary from','Temporary from','Temporary from','Temporary from','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',214,NULL,'to','to','to','to','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',215,NULL,'Proposed by','Proposed by','Proposed by','Proposed by','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',216,NULL,'reviewed by','reviewed by','reviewed by','reviewed by','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',217,NULL,'Approved','Approved','Approved','Approved','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',218,NULL,'not Approved','not Approved','not Approved','not Approved','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',219,NULL,'Verified by','Verified by','Verified by','Verified by','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',220,NULL,'Requestor','Requestor','Requestor','Requestor','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',221,NULL,'Department Manager','Department Manager','Department Manager','Department Manager','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',222,NULL,'Director','Director','Director','Director','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',223,NULL,'Human Resources','Human Resources','Human Resources','Human Resources','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',224,NULL,'Date','Date','Date','Date','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',301,NULL,'For Human Resources/Department only','For Human Resources/Department only','For Human Resources/Department only','For Human Resources/Department only','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',302,NULL,'Received by','Received by','Received by','Received by','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',303,NULL,'Received date','Received date','Received date','Received date','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',401,NULL,'Checklist for Talent Acquisition Team','Checklist for Talent Acquisition Team','Checklist for Talent Acquisition Team','Checklist for Talent Acquisition Team','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',402,NULL,'Document','Document','Document','Document','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',403,NULL,'Job Description','Job Description','Job Description','Job Description','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',404,NULL,'Organization Chart','Organization Chart','Organization Chart','Organization Chart','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',405,NULL,'Remark','Remark','Remark','Remark','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',406,NULL,'Review by','Review by','Review by','Review by','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('hrrcz1x_report',407,NULL,'Date','Date','Date','Date','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
commit;
