SET DEFINE OFF;
DELETE TAPPPROF WHERE CODAPP = 'HRRCZ1X';
INSERT INTO HAFU.TAPPPROF (CODAPP, TYPAPP, CODPROC, DESAPPE, DESAPPT, DESAPP3, DESAPP4, DESAPP5, DESREPE, DESREPT, DESREP3, DESREP4, DESREP5, TYPREP, TYPFORM, DTECREATE, CODCREATE, DTEUPD, CODUSER) VALUES ('HRRCZ1X', 'R', 'RC', 'HRRCZ1X', 'HRRCZ1X', 'HRRCZ1X', 'HRRCZ1X', 'HRRCZ1X', 'HRRCZ1X', 'HRRCZ1X', 'HRRCZ1X', 'HRRCZ1X', 'HRRCZ1X', 'P', null, TIMESTAMP '2024-08-20 17:15:29', null, TIMESTAMP '2024-08-20 17:15:29', 'TJS0000X');
COMMIT;
