SET DEFINE OFF;

DELETE TAPPLSCR WHERE CODAPP like '%HRTRZ1X%';


Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X3',10,null,'Evaluation Training Course','Evaluation Training Courses','Evaluation Training Courses','Evaluation Training Courses','Evaluation Training Courses',to_date('16/08/2024 17:53:14','dd/mm/yyyy hh24:mi:ss'),null,to_date('18/08/2024 22:56:22','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X3',20,null,'Course','Course','Course','Course','Course',to_date('16/08/2024 17:53:15','dd/mm/yyyy hh24:mi:ss'),null,to_date('16/08/2024 17:53:15','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X3',30,null,'Date','Date','Date','Date','Date',to_date('16/08/2024 17:53:15','dd/mm/yyyy hh24:mi:ss'),null,to_date('16/08/2024 17:53:15','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X3',40,null,'Duration','Duration','Duration','Duration','Duration',to_date('16/08/2024 17:53:15','dd/mm/yyyy hh24:mi:ss'),null,to_date('16/08/2024 17:53:15','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X3',50,null,'Venue','Venue','Venue','Venue','Venue',to_date('16/08/2024 17:53:15','dd/mm/yyyy hh24:mi:ss'),null,to_date('16/08/2024 17:53:15','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X3',60,null,'Trainers','Trainers','Trainers','Trainers','Trainers',to_date('16/08/2024 17:53:15','dd/mm/yyyy hh24:mi:ss'),null,to_date('16/08/2024 17:53:15','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X3',70,null,'Actual participants','Actual participants','Actual participants','Actual participants','Actual participants',to_date('16/08/2024 18:01:53','dd/mm/yyyy hh24:mi:ss'),null,to_date('16/08/2024 18:01:53','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X3',80,null,'Evaluate by','Evaluate by','Evaluate by','Evaluate by','Evaluate by',to_date('16/08/2024 18:01:53','dd/mm/yyyy hh24:mi:ss'),null,to_date('16/08/2024 18:01:53','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X3',90,null,'people','people','people','people','people',to_date('16/08/2024 18:01:53','dd/mm/yyyy hh24:mi:ss'),null,to_date('16/08/2024 18:01:53','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X3',100,null,'Accounted for','Accounted for','Accounted for','Accounted for','Accounted for',to_date('16/08/2024 18:01:53','dd/mm/yyyy hh24:mi:ss'),null,to_date('16/08/2024 18:01:53','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X3',110,null,'No.','No.','No.','No.','No.',to_date('16/08/2024 18:01:53','dd/mm/yyyy hh24:mi:ss'),null,to_date('16/08/2024 18:01:53','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X3',120,null,'Topics','Topics','Topics','Topics','Topics',to_date('16/08/2024 18:01:53','dd/mm/yyyy hh24:mi:ss'),null,to_date('16/08/2024 18:01:53','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X3',130,null,'Total Score','Total Score','Total Score','Total Score','Total Score',to_date('16/08/2024 18:01:53','dd/mm/yyyy hh24:mi:ss'),null,to_date('16/08/2024 18:01:53','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X3',140,null,'Average Score','Average Score','Average Score','Average Score','Average Score',to_date('16/08/2024 18:01:53','dd/mm/yyyy hh24:mi:ss'),null,to_date('16/08/2024 18:01:53','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X3',150,null,'วิทยากร (Trainer)','วิทยากร (Trainer)','วิทยากร (Trainer)','วิทยากร (Trainer)','วิทยากร (Trainer)',to_date('16/08/2024 18:01:53','dd/mm/yyyy hh24:mi:ss'),null,to_date('16/08/2024 18:01:53','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X3',160,null,'เนื้อหาการอบรม (Content)','เนื้อหาการอบรม (Content)','เนื้อหาการอบรม (Content)','เนื้อหาการอบรม (Content)','เนื้อหาการอบรม (Content)',to_date('16/08/2024 18:01:53','dd/mm/yyyy hh24:mi:ss'),null,to_date('16/08/2024 18:01:53','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X3',170,null,'รูปแบบการอบรม (Training Style)','รูปแบบการอบรม (Training Style)','รูปแบบการอบรม (Training Style)','รูปแบบการอบรม (Training Style)','รูปแบบการอบรม (Training Style)',to_date('16/08/2024 18:01:53','dd/mm/yyyy hh24:mi:ss'),null,to_date('16/08/2024 18:01:53','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X3',180,null,'ระยะเวลา(จำนวนชั่วโมง)(Training Hour)','ระยะเวลา(จำนวนชั่วโมง)(Training Hour)','ระยะเวลา(จำนวนชั่วโมง)(Training Hour)','ระยะเวลา(จำนวนชั่วโมง)(Training Hour)','ระยะเวลา(จำนวนชั่วโมง)(Training Hour)',to_date('16/08/2024 18:01:53','dd/mm/yyyy hh24:mi:ss'),null,to_date('16/08/2024 18:01:53','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X3',190,null,'สถานที่อบรม (Training Location)','สถานที่อบรม (Training Location)','สถานที่อบรม (Training Location)','สถานที่อบรม (Training Location)','สถานที่อบรม (Training Location)',to_date('16/08/2024 18:01:53','dd/mm/yyyy hh24:mi:ss'),null,to_date('16/08/2024 18:01:53','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X3',200,null,'ผู้ประสานงานการอบรม (Coordinator)','ผู้ประสานงานการอบรม (Coordinator)','ผู้ประสานงานการอบรม (Coordinator)','ผู้ประสานงานการอบรม (Coordinator)','ผู้ประสานงานการอบรม (Coordinator)',to_date('16/08/2024 18:01:54','dd/mm/yyyy hh24:mi:ss'),null,to_date('16/08/2024 18:01:54','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X3',210,null,'ข้อเสนอแนะอื่น ๆ / Any feedback or suggestions','ข้อเสนอแนะอื่น ๆ/ Any feedback or suggestions','ข้อเสนอแนะอื่น ๆ/ Any feedback or suggestions','ข้อเสนอแนะอื่น ๆ/ Any feedback or suggestions','ข้อเสนอแนะอื่น ๆ/ Any feedback or suggestions',to_date('16/08/2024 18:01:54','dd/mm/yyyy hh24:mi:ss'),null,to_date('18/08/2024 23:16:55','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X0',10,null,'year','ปี','year','year','year',to_date('15/08/2024 09:53:37','dd/mm/yyyy hh24:mi:ss'),null,to_date('15/08/2024 09:53:37','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X0',20,null,'Course','หลักสูตร','Course','Course','Course',to_date('15/08/2024 09:53:37','dd/mm/yyyy hh24:mi:ss'),null,to_date('15/08/2024 09:53:37','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X0',30,null,'Generation','รุ่นที่','Generation','Generation','Generation',to_date('15/08/2024 09:53:37','dd/mm/yyyy hh24:mi:ss'),null,to_date('15/08/2024 09:53:37','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X0',40,null,'Training date range','ช่วงวันที่เข้าอบรม','Training date range','Training date range','Training date range',to_date('15/08/2024 09:53:37','dd/mm/yyyy hh24:mi:ss'),null,to_date('15/08/2024 09:53:37','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X0',50,null,'To date','ถึงวันที่','To date','To date','To date',to_date('15/08/2024 09:53:38','dd/mm/yyyy hh24:mi:ss'),null,to_date('15/08/2024 09:53:38','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X1',10,null,'Course','หลักสูตร','Course','Course','Course',to_date('15/08/2024 09:55:56','dd/mm/yyyy hh24:mi:ss'),null,to_date('15/08/2024 09:55:56','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X1',20,null,'Course Name','ชื่อหลักสูตร','Course Name','Course Name','Course Name',to_date('15/08/2024 09:55:56','dd/mm/yyyy hh24:mi:ss'),null,to_date('15/08/2024 09:55:56','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X1',30,null,'generation','รุ่นที่','generation','generation','generation',to_date('15/08/2024 09:55:56','dd/mm/yyyy hh24:mi:ss'),null,to_date('15/08/2024 09:55:56','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X1',40,null,'Training date','วันที่เข้าอบรม','Training date','Training date','Training date',to_date('15/08/2024 09:55:56','dd/mm/yyyy hh24:mi:ss'),null,to_date('15/08/2024 09:55:56','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X1',50,null,'to date','ถึงวันที่','to date','to date','to date',to_date('15/08/2024 09:55:56','dd/mm/yyyy hh24:mi:ss'),null,to_date('15/08/2024 09:55:56','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X1',60,null,'Number of people attending training','จำนวนคนเข้าอบรม','Number of people attending training','Number of people attending training','Number of people attending training',to_date('15/08/2024 09:55:56','dd/mm/yyyy hh24:mi:ss'),null,to_date('15/08/2024 09:55:56','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X1',70,null,'Number of people evaluating','จำนวนคนประเมิน','Number of people evaluating','Number of people evaluating','Number of people evaluating',to_date('15/08/2024 09:55:56','dd/mm/yyyy hh24:mi:ss'),null,to_date('15/08/2024 09:55:56','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X1',80,null,'Total score','คะแนนรวม','Total score','Total score','Total score',to_date('15/08/2024 09:55:56','dd/mm/yyyy hh24:mi:ss'),null,to_date('15/08/2024 09:55:56','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X1',90,null,'Average score','คะแนนเฉลี่ย','Average score','Average score','Average score',to_date('15/08/2024 09:55:57','dd/mm/yyyy hh24:mi:ss'),null,to_date('15/08/2024 09:55:57','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X3',220,null,'ท่านจะนำสิ่งที่ได้รับไปประยุกต์ใช้กับการทำงานของท่านอย่างไร / How will you apply to your work ?','ท่านจะนำสิ่งที่ได้รับไปประยุกต์ใช้กับการทำงานของท่านอย่างไร / How will you apply to your work ?','ท่านจะนำสิ่งที่ได้รับไปประยุกต์ใช้กับการทำงานของท่านอย่างไร / How will you apply to your work ?','ท่านจะนำสิ่งที่ได้รับไปประยุกต์ใช้กับการทำงานของท่านอย่างไร / How will you apply to your work ?','ท่านจะนำสิ่งที่ได้รับไปประยุกต์ใช้กับการทำงานของท่านอย่างไร / How will you apply to your work ?',to_date('17/08/2024 10:12:19','dd/mm/yyyy hh24:mi:ss'),null,to_date('17/08/2024 10:13:19','dd/mm/yyyy hh24:mi:ss'),null);
Insert into TAPPLSCR (CODAPP,NUMSEQ,TYPSCR,DESCLABELE,DESCLABELT,DESCLABEL3,DESCLABEL4,DESCLABEL5,DTECREATE,CODCREATE,DTEUPD,CODUSER) values ('HRTRZ1X3',230,null,'สิ่งที่ท่านอยากแนะนำ หากมีการจัดอบรมหลักสูตรนี้ในครั้งถัดไป / Any feedback or suggestions that are beneficial to training next time.','สิ่งที่ท่านอยากแนะนำ หากมีการจัดอบรมหลักสูตรนี้ในครั้งถัดไป / Any feedback or suggestions that are beneficial to training next time.','สิ่งที่ท่านอยากแนะนำ หากมีการจัดอบรมหลักสูตรนี้ในครั้งถัดไป / Any feedback or suggestions that are beneficial to training next time.','สิ่งที่ท่านอยากแนะนำ หากมีการจัดอบรมหลักสูตรนี้ในครั้งถัดไป / Any feedback or suggestions that are beneficial to training next time.','สิ่งที่ท่านอยากแนะนำ หากมีการจัดอบรมหลักสูตรนี้ในครั้งถัดไป / Any feedback or suggestions that are beneficial to training next time.',to_date('17/08/2024 10:12:19','dd/mm/yyyy hh24:mi:ss'),null,to_date('17/08/2024 10:14:06','dd/mm/yyyy hh24:mi:ss'),null);


COMMIT;