SET DEFINE OFF;
DELETE FROM TAPPLSCR WHERE CODAPP='HRESH6X0';
DELETE FROM TAPPLSCR WHERE CODAPP='HRESH6X1';
DELETE FROM TAPPLSCR WHERE CODAPP='HRESH6X2';
DELETE FROM TAPPLSCR WHERE CODAPP='HRESH6X3';
INSERT INTO TAPPLSCR VALUES ('HRESH6X0',10,NULL,'From year','ตั้งแต่ปี','From year','From year','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X0',20,NULL,'To year','ถึงปี','To year','To year','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X1',10,NULL,'Employee code','รหัสพนักงาน','Employee code','Employee code','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X1',20,NULL,'From year','ตั้งแต่ปี','From year','From year','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X1',30,NULL,'To year','ถึงปี','To year','To year','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X1',40,NULL,'Year','ปี','Year','Year','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X1',50,NULL,'Course code','รหัสหลักสูตร','Course code','Course code','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X1',60,NULL,'Course name','ชื่อหลักสูตร','Course name','Course name','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X1',70,NULL,'Category code','รหัสหมวด','Category code','Category code','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X1',80,NULL,'Category name','ชื่อหมวด','Category name','Category name','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X1',90,NULL,'Training type','ประเภทการอบรม','Training type','Training type','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X1',100,NULL,'Generation','รุ่นที่','Generation','Generation','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X1',110,NULL,'Date of attendance','วันที่เข้าอบรม','Date of attendance','Date of attendance','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X1',120,NULL,'Since','ตั้งแต่','Since','Since','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X1',130,NULL,'To','ถึง','To','To','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X1',140,NULL,'Hours','จำนวนชั่วโมง','Hours','Hours','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X1',150,NULL,'The cost','ค่าใช้จ่าย','The cost','The cost','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X1',160,NULL,'Potential assessment results','ผลการประเมินศักยภาพ','Potential assessment results','Potential assessment results','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X1',170,NULL,'Obligation','สัญญาผูกมัด','Obligation','Obligation','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X2',10,NULL,'Training Report','Training Report','Training Report','Training Report','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X2',20,NULL,'Employee Code','รหัสพนักงาน','Employee Code','Employee Code','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X2',30,NULL,'Department Name','ชื่อหน่วยงาน','Department Name','Department Name','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X2',40,NULL,'Position Name','ตำแหน่ง','Position Name','Position Name','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X2',50,NULL,'Course Name','ชื่อหลักสูตร','Course Name','Course Name','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X2',60,NULL,'Date Train','วันที่เข้าอบรม','Date Train','Date Train','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X2',70,NULL,'Class No','รุ่นที่','Class No','Class No','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X2',80,NULL,'Description','รายละเอียดการเข้าอบรม','Description','Description','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X2',90,NULL,'Type Course','ประเภทการอบรม','Type Course','Type Course','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X2',100,NULL,'Internal','ภายใน','Internal','Internal','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X2',110,NULL,'Location','สถานที่จัดอบรม','Location','Location','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X2',120,NULL,'Institute','สถาบัน','Institute','Institute','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X2',130,NULL,'Date Train','วันที่อบรม','Date Train','Date Train','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X2',140,NULL,'Qty. Hour','จำนวนชั่วโมงอบรม','Qty. Hour','Qty. Hour','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X2',145,NULL,'Hour','ชั่วโมง','Hour','Hour','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X2',150,NULL,'Amout','ค่าใช้จ่าย','Amout','Amout','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X2',155,NULL,'Bath/Person','บาท/คน','Bath/Person','Bath/Person','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X2',160,NULL,'Type','ประเภทการพัฒนา','Type','Type','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X2',170,NULL,'Result','ผลการฝึกอบรม','Result','Result','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X2',180,NULL,'Score Pre test','คะแนน Pre test','Score Pre test','Score Pre test','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X2',190,NULL,'Score Post test','คะแนน Post test','Score Post test','Score Post test','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X2',200,NULL,'Assessment results','ผลการประเมิน','Assessment results','Assessment results','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X2',210,NULL,'Potential assessment results','ผลการประเมินศักยภาพ','Potential assessment results','Potential assessment results','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X2',220,NULL,'Summary of information gained from training','สรุปข้อมูลที่ได้จากการอบรม','Summary of information gained from training','Summary of information gained from training','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X2',230,NULL,'Subject','เรื่อง','Subject','Subject','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X2',240,NULL,'Attach File','Attach File','Attach File','Attach File','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X2',250,NULL,'URL','URL','URL','URL','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X2',260,NULL,'Benefits received from training','ประโยชน์ที่ได้รับจากการอบรม','Benefits received from training','Benefits received from training','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X2',270,NULL,'Description','รายละเอียด','Description','Description','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',10,NULL,'Training Report (External)','รายงานรายละเอียดการเข้าอมรม (ภายนอก)','Training Report (External)','Training Report (External)','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',20,NULL,'Employee Code','รหัสพนักงาน','Employee Code','Employee Code','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',30,NULL,'Department Name','ชื่อหน่วยงาน','Department Name','Department Name','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',40,NULL,'Position Name','ตำแหน่ง','Position Name','Position Name','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',45,NULL,'Year','ปี','Year','Year','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',50,NULL,'Course Name','ชื่อหลักสูตร','Course Name','Course Name','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',60,NULL,'Date Train','วันที่เข้าอบรม','Date Train','Date Train','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',70,NULL,'Class No','รุ่นที่','Class No','Class No','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',80,NULL,'Description','รายละเอียดการเข้าอบรม','Description','Description','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',90,NULL,'Type Course','ประเภทการอบรม','Type Course','Type Course','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',100,NULL,'External','ภายนอก','External','External','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',110,NULL,'Location','สถานที่จัดอบรม','Location','Location','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',120,NULL,'Institute','สถาบันจัดอบรม','Institute','Institute','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',130,NULL,'Trainer','ชื่อวิทยากร','Trainer','Trainer','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',140,NULL,'Qty. Hour','จำนวนชั่วโมงอบรม','Qty. Hour','Qty. Hour','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',145,NULL,'Hour','ชั่วโมง','Hour','Hour','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',150,NULL,'Amout','ค่าใช้จ่ายรวม','Amout','Amout','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',155,NULL,'Bath','บาท','Bath','Bath','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',160,NULL,'Cert No.','เลขที่ใบรับรอง','Cert No.','Cert No.','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',165,NULL,'Cert Date','วันที่รับรอง','Cert Date','Cert Date','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',170,NULL,'Cert Approve By','หน่วยงานที่ออกหนังสือ','Cert Approve By','Cert Approve By','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',180,NULL,'Document Approve','มีหลักฐานแสดงผ่านการอบรม','Document Approve','Document Approve','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',190,NULL,'Abstract','เนื้อหาการอบรมโดยย่อ','Abstract','Abstract','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',200,NULL,'Result','ผลการประเมิน','Result','Result','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',210,NULL,'Result','ผลการประเมินศักยภาพ','Result','Result','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',220,NULL,'Summary of information gained from training','สรุปข้อมูลที่ได้จากการอบรม','Summary of information gained from training','Summary of information gained from training','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',230,NULL,'Subject','เรื่อง','Subject','Subject','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',240,NULL,'Attach File','Attach File','Attach File','Attach File','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',250,NULL,'URL','URL','URL','URL','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',260,NULL,'Benefits received from training','ประโยชน์ที่ได้รับจากการอบรม','Benefits received from training','Benefits received from training','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',270,NULL,'Description','รายละเอียด','Description','Description','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',280,NULL,'Cost Detail','รายละเอียดค่าใช้จ่าย','Cost Detail','Cost Detail','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',290,NULL,'Cost code','รหัสค่าใช้จ่าย','Cost code','Cost code','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',295,NULL,'Description','รายละเอียด','Description','Description','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',300,NULL,'Type','ประเภทค่าใช้จ่าย','Type','Type','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',310,NULL,'Amout','จำนวนเงิน','Amout','Amout','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',320,NULL,'Expenses sent to the Department of Development','ค่าใช้จ่ายส่งกรมพัฒฯ','Expenses sent to the Department of Development','Expenses sent to the Department of Development','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',330,NULL,'Action plan after training','แผนดำเนินการหลังอบรม','Action plan after training','Action plan after training','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',340,NULL,'Action plan','แผนการปฏิบัติงาน','Action plan','Action plan','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',350,NULL,'Target Date','Target Date','Target Date','Target Date','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',360,NULL,'Start','ตั้งแต่','Start','Start','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',370,NULL,'To','ถึง','To','To','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',380,NULL,'Progress','ความคืบหน้า','Progress','Progress','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',390,NULL,'Sum','รวม','Sum','Sum','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',400,NULL,'Attachment','เอกสารแนบ','Attachment','Attachment','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',410,NULL,'File name','ชื่อไฟล์','File name','File name','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',420,NULL,'Detail','รายละเอียด','Detail','Detail','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',430,NULL,'Have','มี','Have','Have','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
INSERT INTO TAPPLSCR VALUES ('HRESH6X3',440,NULL,'Without','ไม่มี','Without','Without','undefined',SYSDATE,NULL,SYSDATE,'TJS00001');
commit;
